# AWS Load Balancer Controller 간단 설치
# 이 파일을 kubectl apply로 실행하면 됩니다

---
# 1. ServiceAccount 생성
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::324547056370:role/AmazonEKSLoadBalancerControllerRole

---
# 2. CertManager 설치 (필수)
# 먼저 다음 명령어 실행:
# kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.13.0/cert-manager.yaml

---
# 3. AWS Load Balancer Controller 설치
# 다음 명령어 실행:
# kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
# helm repo add eks https://aws.github.io/eks-charts
# helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=fproject-dev-eks --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller
